#!/usr/bin/env bash
# A bash script that displays the time for 12 hours and 59 minutes: display hours from 0 to 12, display minutes from 1 to 59 using while loop
i=0
while ((i < 12))
do
	echo "Hour: "$i
	n=1
	while ((n < 60))
	do
		echo $n
		((n+=1))
	done
	((i+=1))
done
